### PR TITLE
Checkbox test

### LINKED ISSUE #19: Rework CheckboxTest
The website that was originally used for the CheckBoxTest was reworked by the owner of the site. Now the tests fail. They need to be reworked in order to work again.

### PR DESCRIPTION
**Pull request by georgkunze**
#19 
Website that was used for the Checkbox test was changed, so the tests neede to be adapted.
The test for the neseted shadow dom now does not really test something usefull, but shows the correct usage of the shadowDom function for nested shadow doms

### CODE REVIEW

**Comment by jseng92** [comment]
rechecked! no hints or changes from my side.

**Review by ckeiner — CHANGES_REQUESTED** [review]
The test suite does not currently run without ignoring certificate erros in chrome, i.e. `browserprofile.Chrome_1024x768.arguments = -ignore-certificate-errors`. Please add the property to the relevant browsers.

**Comment by ckeiner** [comment]
> The test suite does not currently run without ignoring certificate erros in chrome, i.e. `browserprofile.Chrome_1024x768.arguments = -ignore-certificate-errors`. Please add the property to the relevant browsers.

Note, that we should do this for all Chromes and recheck if it works in Firefox, so users can change the browser and the tests still work

**Comment by georgkunze** [comment]
@ckeiner i added the `-ignore-certificate-errors` option to both Chrome and Firefox browserprofils and checked that the test is still working with firefox

File: config/browser.properties [hunk 1]
```diff
@@ -89,21 +89,25 @@
...
 browserprofile.Chrome_1500x1000.name = Chrome 1500x1000
 browserprofile.Chrome_1500x1000.browser = chrome
 browserprofile.Chrome_1500x1000.browserResolution = 1500x1000
+browserprofile.Chrome_1500x1000.arguments = -ignore-certificate-errors
 
 # Small Firefox
 browserprofile.FF_1024x768.name = Firefox 1024x768
 browserprofile.FF_1024x768.browser = firefox
 browserprofile.FF_1024x768.browserResolution = 1024x768
+browserprofile.FF_1024x768.arguments = -ignore-certificate-errors
```
Comment (ckeiner) [inline config/browser.properties]: Unfortunately, Firefox does not have such an argument.
```suggestion
```

File: config/browser.properties [hunk 2]
```diff
@@ -89,21 +89,25 @@
...
 
 # Local Firefox but with larger window size
 browserprofile.FF_1500x1000.name = Latest local Firefox 1500x1000
 browserprofile.FF_1500x1000.browser = firefox
 browserprofile.FF_1500x1000.screenResolution = 1500x1000
+browserprofile.FF_1500x1000.arguments = -ignore-certificate-errors
```
Comment (ckeiner) [inline config/browser.properties]: Unfortunately, Firefox does not have such an argument.
```suggestion
```

File: src/test/java/showcase/neodymium/tests/shadowdom/CheckboxTest.java [hunk 3]
```diff
@@ -34,6 +35,8 @@
         
     @Test
     @Description(value = "Showcase for nested shadow DOM.")
+    @Browser("FF_1024x768")
+    @Browser("Chrome_1024x768")
```
Comment (ckeiner) [inline src/test/java/showcase/neodymium/tests/shadowdom/CheckboxTest.java]: You don't need to add these as the browser should be controller by `AbstractTest`. And since we don't have a Firefox configured there, I would not add it anywhere.

**Review by ckeiner — CHANGES_REQUESTED** [review]

File: src/test/java/showcase/neodymium/tests/shadowdom/CheckboxTest.java [hunk 4]
```diff
@@ -31,76 +29,77 @@
...
+        // shadowCss(target-element, parent-shadow-host, list-of-nested-shadow-hosts)
+        // Note: the last parameter excepts either a simple string or a list of strings
+        // the list has to contain in order all the nested shadow hosts that need to be
+        // found, to be able to find the target element.
         $(Selectors.shadowCss(target, shadowHost, nestedShadowHost)).shouldNotBe(visible);
     }
-    
-    //@Test
+
+    // @Test
```
Comment (ckeiner) [inline src/test/java/showcase/neodymium/tests/shadowdom/CheckboxTest.java]: Should this really be commented out?

**Review by ckeiner — CHANGES_REQUESTED** [review]

File: src/test/java/showcase/neodymium/tests/shadowdom/CheckboxTest.java (hunk 4 above)
Comment (georgkunze) [reply src/test/java/showcase/neodymium/tests/shadowdom/CheckboxTest.java]: Nope, my mistake.

**Review by ckeiner — APPROVED** [review]
